import Section from "../components/Section";
import { gradient } from "../assets";
import config from '../config/config';

const PolicySection = ({ title, subtitle, children }) => (
  <div className="mb-8">
    {title && (
      <h2 className="text-2xl font-semibold text-n-1 mb-4">
        {title}
      </h2>
    )}
    {subtitle && (
      <h3 className="text-lg font-semibold text-n-1 mb-2">
        {subtitle}
      </h3>
    )}
    <div className="text-n-3 text-base leading-relaxed space-y-4">
      {children}
    </div>
  </div>
);

const Privacy = () => {
  return (
    <Section className="pt-[12rem] -mt-[5.25rem]" crosses>
      <div className="container relative">
        <div className="relative z-1 max-w-[62rem] mx-auto">
          <div className="bg-n-8 border border-n-6 rounded-2xl p-8">
            <h1 className="text-3xl font-bold text-n-1 mb-2">Privacy Policy</h1>
            <p className="text-n-3 text-sm mb-8">
              Last updated: January 27, 2025
            </p>

            <PolicySection>
              <p>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </p>
              <p>
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
              </p>
            </PolicySection>

            <PolicySection title="Interpretation and Definitions" subtitle="Interpretation">
              <p>
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>
            </PolicySection>

            <PolicySection subtitle="Definitions">
              <p>
                For the purposes of this Privacy Policy:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Account means a unique account created for You to access our Service or parts of our Service.</li>
                <li>Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li>Application refers to DocuTalk, the software program provided by the Company.</li>
                <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to DocuTalk.</li>
                <li>Country refers to: United Kingdom</li>
                <li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li>Personal Data is any information that relates to an identified or identifiable individual.</li>
                <li>Service refers to the Application.</li>
                <li>Service Provider means any natural or legal person who processes the data on behalf of the Company.</li>
                <li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
            </PolicySection>

            <PolicySection title="Collecting and Using Your Personal Data" subtitle="Types of Data Collected">
              <div className="space-y-4">
                <div>
                  <p className="font-medium mb-2">Personal Data</p>
                  <p>
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                  </p>
                  <ul className="list-disc pl-6 mt-2">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Usage Data</li>
                  </ul>
                </div>
                <div>
                  <p className="font-medium mb-2">Usage Data</p>
                  <p>
                    Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address, browser type, browser version, unique device identifiers and other diagnostic data.
                  </p>
                </div>
              </div>
            </PolicySection>

            <PolicySection title="Contact Us">
              <p>
                If you have any questions about this Privacy Policy, You can contact us:
              </p>
              <p className="mt-2">
                By email: cust.supp.docutalk@gmail.com
              </p>
            </PolicySection>
          </div>
        </div>

        {/* Background gradient */}
        <div className="absolute top-0 -left-[10rem] w-[56.625rem] h-[56.625rem] opacity-50 mix-blend-color-dodge pointer-events-none">
          <img
            className="absolute top-1/2 left-1/2 w-[79.5625rem] h-[88.5625rem] -translate-x-1/2 -translate-y-1/2"
            src={gradient}
            alt="Gradient"
          />
        </div>
      </div>
    </Section>
  );
};

export default Privacy; 